---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true

driver:
  name: podman

platforms:
  - name: instance
    image: registry.access.redhat.com/ubi9/ubi:latest
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    privileged: true
    command: "sleep infinity"
    capabilities:
      - SYS_ADMIN

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        cifmw_snr_nhc_kubeconfig: "/tmp/kubeconfig"
        cifmw_snr_nhc_kubeadmin_password_file: "/tmp/kubeadmin-password"
        cifmw_snr_nhc_namespace: "test-workload-availability"
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
