---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if Python kubernetes library is installed
      ansible.builtin.command: >-
        python3 -c "import kubernetes; print('kubernetes library version:', kubernetes.__version__)"
      register: k8s_lib_check
      changed_when: false

    - name: Display kubernetes library version
      ansible.builtin.debug:
        msg: "{{ k8s_lib_check.stdout }}"

    - name: Verify kubeconfig mock file exists
      ansible.builtin.stat:
        path: /tmp/kubeconfig
      register: kubeconfig_verify

    - name: Assert kubeconfig mock file exists
      ansible.builtin.assert:
        that:
          - kubeconfig_verify.stat.exists
        fail_msg: "Mock kubeconfig file was not created"
        success_msg: "Mock kubeconfig file exists"

    - name: Verify kubeadmin password mock file exists
      ansible.builtin.stat:
        path: /tmp/kubeadmin-password
      register: kubeadmin_verify

    - name: Assert kubeadmin password mock file exists
      ansible.builtin.assert:
        that:
          - kubeadmin_verify.stat.exists
        fail_msg: "Mock kubeadmin password file was not created"
        success_msg: "Mock kubeadmin password file exists"

    - name: Test Python yaml library
      ansible.builtin.command: python3 -c "import yaml; print('yaml library works')"
      register: yaml_check
      changed_when: false

    - name: Display yaml test result
      ansible.builtin.debug:
        msg: "{{ yaml_check.stdout }}"
