---
- name: Execute Self Node Remediation role
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  vars:
    cifmw_snr_nhc_cleanup_before_install: "{{ cleanup_before_install | default(false) }}"
    cifmw_snr_nhc_cleanup_namespace: "{{ cleanup_namespace | default(false) }}"
  roles:
    - cifmw_snr_nhc
